site_name: Rodriguez LeRobot

theme:
  name: 'readthedocs'

site_url: https://zahirmahammad.github.io/rodriguezlerobot/


nav:
  - Introduction: index.md
  - Initial Setup: InitialSetup.md
  - Control the Robot: Control.md